export const data={
    "'dialog(cr3b2_test.topic.Untitled)'.DisplayName": "Entity extract - Test",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(question_YtFMIB)'.Prompt.Text[0]": "Choose",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(question_YtFMIB)'.Entity.Definition.'closedListItem(name and mail)'.DisplayName": "name and mail",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(question_YtFMIB)'.Entity.Definition.'closedListItem(name, mail, city)'.DisplayName": "name, mail, city",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(question_YtFMIB)'.Entity.Definition.'closedListItem(name, age, ph, mail)'.DisplayName": "name, age, ph, mail",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(question_YtFMIB)'.Entity.Definition.'closedListItem(name, mail, contact)'.DisplayName": "name, mail, contact",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(question_ogwqzN)'.Prompt.Text[0]": "Enter",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(question_IUTE9r)'.Prompt.Text[0]": "enter mail",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(sendActivity_iMCqZp)'.Activity.Text[0]": "{Topic.Var2}, {Topic.Var3}\u200A",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(question_oDLZtk)'.Prompt.Text[0]": "Enter",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(question_c9n5oI)'.Prompt.Text[0]": "mail",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(question_9EIoiC)'.Prompt.Text[0]": "city",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(sendActivity_3xCsNS)'.Activity.Text[0]": "{Topic.Var4}, {Topic.Var5}\u200A, {Topic.Var6}\u200A",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(question_Cq2152)'.Prompt.Text[0]": "Enter",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(question_xBbATP)'.Prompt.Text[0]": "age",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(question_OZl75M)'.Prompt.Text[0]": "phone",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(question_y8dRYb)'.Prompt.Text[0]": "mail",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(sendActivity_KjCSfv)'.Activity.Text[0]": "{Topic.Var7}, {Topic.Var8}\u200A, {Topic.Var9}\u200A, {Topic.Var10}\u200A",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(question_mpzfkl)'.Prompt.Text[0]": "Enter",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(question_9AZliy)'.Prompt.Text[0]": "mail",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(question_SNcYHA)'.Prompt.Text[0]": "phone",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.'action(sendActivity_dRNqM5)'.Activity.Text[0]": "{Topic.Var11}, {Topic.Var12}\u200A, {Topic.Var13}\u200A",
    "'dialog(cr3b2_test.topic.Untitled)'.'trigger(main)'.Intent.TriggerQueries[0]": "group",
    "'dialog(cr3b2_test.topic.Lesson1)'.DisplayName": "Lesson 1 - A simple topic",
    "'dialog(cr3b2_test.topic.Lesson1)'.'trigger(main)'.'action(Ystyaa)'.Activity.Text[0]": "I'm happy to help with store hours.",
    "'dialog(cr3b2_test.topic.Lesson1)'.'trigger(main)'.'action(6Jn5pw)'.Activity.Text[0]": "The Redmond hours are:\n- Mon-Fri: 9am to 6pm\n- Sat: 10am to 4pm\n- Sun: Closed\n\nThe Seattle hours are:\n- Mon-Fri: 9am to 6pm\n- Sat-Sun: 10am to 4pm",
    "'dialog(cr3b2_test.topic.Lesson1)'.'trigger(main)'.Intent.DisplayName": "Lesson 1 - A simple topic",
    "'dialog(cr3b2_test.topic.Lesson1)'.'trigger(main)'.Intent.TriggerQueries[0]": "When are you closed",
    "'dialog(cr3b2_test.topic.Lesson1)'.'trigger(main)'.Intent.TriggerQueries[1]": "When are you open",
    "'dialog(cr3b2_test.topic.Lesson1)'.'trigger(main)'.Intent.TriggerQueries[2]": "Store hours",
    "'dialog(cr3b2_test.topic.Lesson1)'.'trigger(main)'.Intent.TriggerQueries[3]": "Daily open hours",
    "'dialog(cr3b2_test.topic.Fallback)'.DisplayName": "Fallback",
    "'dialog(cr3b2_test.topic.Fallback)'.Description": "This system topic triggers when the user's utterance does not match any existing topics.",
    "'dialog(cr3b2_test.topic.Fallback)'.'trigger(main)'.'action(sendMessage_QZreqo)'.Activity.Text[0]": "I'm sorry, I'm not sure how to help with that. Can you try rephrasing?",
    "'dialog(cr3b2_test.topic.Createentity-Test)'.DisplayName": "Create entity - Test",
    "'dialog(cr3b2_test.topic.Createentity-Test)'.'trigger(main)'.'action(question_7Zs3cC)'.Prompt.Text[0]": "Choose",
    "'dialog(cr3b2_test.topic.Createentity-Test)'.'trigger(main)'.'action(question_7Zs3cC)'.Entity.Definition.'closedListItem(list items)'.DisplayName": "list items",
    "'dialog(cr3b2_test.topic.Createentity-Test)'.'trigger(main)'.'action(question_7Zs3cC)'.Entity.Definition.'closedListItem(items with synonyms)'.DisplayName": "items with synonyms",
    "'dialog(cr3b2_test.topic.Createentity-Test)'.'trigger(main)'.'action(question_VR5h9e)'.UnrecognizedPrompt.Text[0]": "Invalid shop. Please enter a valid shop name!",
    "'dialog(cr3b2_test.topic.Createentity-Test)'.'trigger(main)'.'action(question_VR5h9e)'.Prompt.Text[0]": "Enter shop",
    "'dialog(cr3b2_test.topic.Createentity-Test)'.'trigger(main)'.'action(sendActivity_bzFc6L)'.Activity.Text[0]": "{Topic.Var2}.",
    "'dialog(cr3b2_test.topic.Createentity-Test)'.'trigger(main)'.'action(question_EBHog9)'.UnrecognizedPrompt.Text[0]": "Enter a valid one!",
    "'dialog(cr3b2_test.topic.Createentity-Test)'.'trigger(main)'.'action(question_EBHog9)'.Prompt.Text[0]": "Enter data",
    "'dialog(cr3b2_test.topic.Createentity-Test)'.'trigger(main)'.'action(sendActivity_zo5xIX)'.Activity.Text[0]": "{Topic.Var3}",
    "'dialog(cr3b2_test.topic.Createentity-Test)'.'trigger(main)'.Intent.TriggerQueries[0]": "create",
    "'dialog(cr3b2_test.topic.OnError)'.DisplayName": "On Error",
    "'dialog(cr3b2_test.topic.OnError)'.Description": "This system topic triggers when the bot encounters an error. When using the test chat pane, the full error description is displayed.",
    "'dialog(cr3b2_test.topic.OnError)'.'trigger(main)'.'action(sendMessage_XJBYMo)'.Activity.Text[0]": "Error Message: {System.Error.Message}\nError Code: {System.Error.Code}\nConversation Id: {System.Conversation.Id}\nTime (UTC): {Topic.CurrentTime}",
    "'dialog(cr3b2_test.topic.OnError)'.'trigger(main)'.'action(sendMessage_dZ0gaF)'.Activity.Text[0]": "An error has occurred.\nError code: {System.Error.Code}\nConversation Id: {System.Conversation.Id}\nTime (UTC): {Topic.CurrentTime}.",
    "'dialog(cr3b2_test.topic.OnError)'.'trigger(main)'.'action(sendMessage_dZ0gaF)'.Activity.Speak[0]": "An error has occurred, please try again.",
    "'dialog(cr3b2_test.topic.ConversationStart)'.DisplayName": "Conversation Start",
    "'dialog(cr3b2_test.topic.ConversationStart)'.Description": "This system topic triggers when the bot receives an Activity indicating the beginning of a new conversation. If do not want the bot to initiate the conversation, disable this topic.",
    "'dialog(cr3b2_test.topic.ConversationStart)'.'trigger(main)'.'action(sendMessage_M0LuhV)'.Activity.Text[0]": "Hello, I'm {System.Bot.Name}, a virtual assistant. Just so you are aware, I sometimes use AI to answer your questions. How can I help?",
    "'dialog(cr3b2_test.topic.ConversationStart)'.'trigger(main)'.'action(sendMessage_M0LuhV)'.Activity.Speak[0]": "Thanks for calling, how can I help?",
    "'dialog(cr3b2_test.topic.Lesson2)'.DisplayName": "Lesson 2 - A simple topic with a condition and variable",
    "'dialog(cr3b2_test.topic.Lesson2)'.'trigger(main)'.'action(qvduia)'.Activity.Text[0]": "I'd be glad to help find a store near you.",
    "'dialog(cr3b2_test.topic.Lesson2)'.'trigger(main)'.'action(LbWwpD)'.Prompt.Text[0]": "Which location are you interested in?",
    "'dialog(cr3b2_test.topic.Lesson2)'.'trigger(main)'.'action(LbWwpD)'.Entity.Definition.'closedListItem(Redmond)'.DisplayName": "Redmond",
    "'dialog(cr3b2_test.topic.Lesson2)'.'trigger(main)'.'action(LbWwpD)'.Entity.Definition.'closedListItem(Seattle)'.DisplayName": "Seattle",
    "'dialog(cr3b2_test.topic.Lesson2)'.'trigger(main)'.'action(LbWwpD)'.Entity.Definition.'closedListItem(Kirkland)'.DisplayName": "Kirkland",
    "'dialog(cr3b2_test.topic.Lesson2)'.'trigger(main)'.'action(khIIPE)'.Activity.Text[0]": "Check out the Company Store at our Visitor Center. The address is: 4567 Main St., Redmond, 26132.",
    "'dialog(cr3b2_test.topic.Lesson2)'.'trigger(main)'.'action(X7eulp)'.Activity.Text[0]": "Our {Topic.StoreLocation} store is located in the U District in the University Village. The address is: 1234 E. University Village St., Seattle, 34567.",
    "'dialog(cr3b2_test.topic.Lesson2)'.'trigger(main)'.'action(jtQo0O)'.Activity.Text[0]": "Our\u00A0{Topic.StoreLocation} is located in downtown Kirkland. The address is: 1234 Central Way, Kirkland, 98321.",
    "'dialog(cr3b2_test.topic.Lesson2)'.'trigger(main)'.Intent.DisplayName": "Lesson 2 - A simple topic with a condition and variable",
    "'dialog(cr3b2_test.topic.Lesson2)'.'trigger(main)'.Intent.TriggerQueries[0]": "Find my nearest store",
    "'dialog(cr3b2_test.topic.Lesson2)'.'trigger(main)'.Intent.TriggerQueries[1]": "Check store location",
    "'dialog(cr3b2_test.topic.Lesson2)'.'trigger(main)'.Intent.TriggerQueries[2]": "Find a store",
    "'dialog(cr3b2_test.topic.Lesson2)'.'trigger(main)'.Intent.TriggerQueries[3]": "Find me your nearest location",
    "'dialog(cr3b2_test.topic.Lesson2)'.'trigger(main)'.Intent.TriggerQueries[4]": "Store near me",
    "'dialog(cr3b2_test.topic.ThankYou)'.DisplayName": "Thank you",
    "'dialog(cr3b2_test.topic.ThankYou)'.Description": "This topic triggers when the user says thank you.",
    "'dialog(cr3b2_test.topic.ThankYou)'.'trigger(main)'.'action(sendMessage_9iz6v7)'.Activity.Text[0]": "You're welcome.",
    "'dialog(cr3b2_test.topic.ThankYou)'.'trigger(main)'.Intent.DisplayName": "Thank you",
    "'dialog(cr3b2_test.topic.ThankYou)'.'trigger(main)'.Intent.TriggerQueries[0]": "thanks",
    "'dialog(cr3b2_test.topic.ThankYou)'.'trigger(main)'.Intent.TriggerQueries[1]": "thank you",
    "'dialog(cr3b2_test.topic.ThankYou)'.'trigger(main)'.Intent.TriggerQueries[2]": "thanks so much",
    "'dialog(cr3b2_test.topic.ThankYou)'.'trigger(main)'.Intent.TriggerQueries[3]": "ty",
    "'dialog(cr3b2_test.topic.StartOver)'.DisplayName": "Start Over",
    "'dialog(cr3b2_test.topic.StartOver)'.'trigger(main)'.'action(question_zguoVV)'.Prompt.Text[0]": "Are you sure you want to restart the conversation?",
    "'dialog(cr3b2_test.topic.StartOver)'.'trigger(main)'.'action(sendMessage_lk2CyQ)'.Activity.Text[0]": "Ok. Let's carry on.",
    "'dialog(cr3b2_test.topic.StartOver)'.'trigger(main)'.Intent.DisplayName": "Start Over",
    "'dialog(cr3b2_test.topic.StartOver)'.'trigger(main)'.Intent.TriggerQueries[0]": "let's begin again",
    "'dialog(cr3b2_test.topic.StartOver)'.'trigger(main)'.Intent.TriggerQueries[1]": "start over",
    "'dialog(cr3b2_test.topic.StartOver)'.'trigger(main)'.Intent.TriggerQueries[2]": "start again",
    "'dialog(cr3b2_test.topic.StartOver)'.'trigger(main)'.Intent.TriggerQueries[3]": "restart",
    "'customEntity(cr3b2_test.entity.ShopNames)'.DisplayName": "ShopNames",
    "'customEntity(cr3b2_test.entity.ShopNames)'.Entity.'closedListItem(nRMpQe)'.DisplayName": "Trends",
    "'customEntity(cr3b2_test.entity.ShopNames)'.Entity.'closedListItem(aAwbBs)'.DisplayName": "Zudio",
    "'customEntity(cr3b2_test.entity.ShopNames)'.Entity.'closedListItem(guzMkJ)'.DisplayName": "Brand factory",
    "'customEntity(cr3b2_test.entity.ShopNames)'.Entity.'closedListItem(9E3G8e)'.DisplayName": "MenZone",
    "'dialog(cr3b2_test.topic.Greeting)'.DisplayName": "Greeting",
    "'dialog(cr3b2_test.topic.Greeting)'.Description": "This topic is triggered when the user greets the bot.",
    "'dialog(cr3b2_test.topic.Greeting)'.'trigger(main)'.'action(sendMessage_abmysR)'.Activity.Text[0]": "Hello, how can I help you today?",
    "'dialog(cr3b2_test.topic.Greeting)'.'trigger(main)'.'action(sendMessage_abmysR)'.Activity.Speak[0]": "Hello, <break strength=\"medium\" /> how can I help?",
    "'dialog(cr3b2_test.topic.Greeting)'.'trigger(main)'.Intent.DisplayName": "Greeting",
    "'dialog(cr3b2_test.topic.Greeting)'.'trigger(main)'.Intent.TriggerQueries[0]": "Good afternoon",
    "'dialog(cr3b2_test.topic.Greeting)'.'trigger(main)'.Intent.TriggerQueries[1]": "Good morning",
    "'dialog(cr3b2_test.topic.Greeting)'.'trigger(main)'.Intent.TriggerQueries[2]": "Hello",
    "'dialog(cr3b2_test.topic.Greeting)'.'trigger(main)'.Intent.TriggerQueries[3]": "Hey",
    "'dialog(cr3b2_test.topic.Greeting)'.'trigger(main)'.Intent.TriggerQueries[4]": "Hi",
    "'dialog(cr3b2_test.topic.EndofConversation)'.DisplayName": "End of Conversation",
    "'dialog(cr3b2_test.topic.EndofConversation)'.Description": "This system topic is only triggered by a redirect action,\nand guides the user through rating their conversation with the bot.",
    "'dialog(cr3b2_test.topic.EndofConversation)'.'trigger(main)'.'action(41d42054-d4cb-4e90-b922-2b16b37fe379)'.Prompt.Text[0]": "Did that answer your question?",
    "'dialog(cr3b2_test.topic.EndofConversation)'.'trigger(main)'.'action(sendMessage_8r29O0)'.Activity.Text[0]": "Thanks for your feedback.",
    "'dialog(cr3b2_test.topic.EndofConversation)'.'trigger(main)'.'action(question_1)'.Prompt.Text[0]": "Can I help with anything else?",
    "'dialog(cr3b2_test.topic.EndofConversation)'.'trigger(main)'.'action(sendMessage_4eOE6h)'.Activity.Text[0]": "Go ahead. I'm listening.",
    "'dialog(cr3b2_test.topic.EndofConversation)'.'trigger(main)'.'action(yHBz55)'.Activity.Text[0]": "Ok, goodbye.",
    "'dialog(cr3b2_test.topic.EndofConversation)'.'trigger(main)'.'action(PM68ot)'.Prompt.Text[0]": "Sorry I wasn't able to help better. Would you like to try again?",
    "'dialog(cr3b2_test.topic.EndofConversation)'.'trigger(main)'.'action(GrVHEW)'.Activity.Text[0]": "Go ahead. I'm listening.",
    "'dialog(cr3b2_test.topic.HTTPTest)'.DisplayName": "HTTP Test",
    "'dialog(cr3b2_test.topic.HTTPTest)'.'trigger(main)'.'action(question_jawTK7)'.Prompt.Text[0]": "Choose",
    "'dialog(cr3b2_test.topic.HTTPTest)'.'trigger(main)'.'action(question_jawTK7)'.Entity.Definition.'closedListItem(HTTP Request from PA)'.DisplayName": "HTTP Request from PA",
    "'dialog(cr3b2_test.topic.HTTPTest)'.'trigger(main)'.'action(question_jawTK7)'.Entity.Definition.'closedListItem(HTTP Request from PVA)'.DisplayName": "HTTP Request from PVA",
    "'dialog(cr3b2_test.topic.HTTPTest)'.'trigger(main)'.'action(sendActivity_DUb66Z)'.Activity.Text[0]": "{Topic.response}",
    "'dialog(cr3b2_test.topic.HTTPTest)'.'trigger(main)'.'action(sendActivity_kdyzlV)'.Activity.Text[0]": "{Topic.Resp.name},\n{Topic.Resp.age}\u200A,\n{Topic.Resp.native}\u200A",
    "'dialog(cr3b2_test.topic.HTTPTest)'.'trigger(main)'.Intent.TriggerQueries[0]": "http",
    "'dialog(cr3b2_test.topic.Signin)'.DisplayName": "Sign in ",
    "'dialog(cr3b2_test.topic.Signin)'.Description": "This system topic triggers when the bot needs to sign in the user or require the user to sign in",
    "'dialog(cr3b2_test.topic.Signin)'.'trigger(main)'.'action(sendMessage_1jHUNO)'.Activity.Text[0]": "Hello! To be able to help you, I'll need you to sign in.",
    "'dialog(cr3b2_test.topic.Signin)'.'trigger(main)'.'action(gOjhZA)'.Title": "Login",
    "'dialog(cr3b2_test.topic.Signin)'.'trigger(main)'.'action(gOjhZA)'.Text": "To continue, please login",
    "'dialog(cr3b2_test.topic.ResetConversation)'.DisplayName": "Reset Conversation",
    "'dialog(cr3b2_test.topic.ResetConversation)'.'trigger(main)'.'action(sendMessage_OPsT1O)'.Activity.Text[0]": "What can I help you with?",
    "'dialog(cr3b2_test.topic.MultipleTopicsMatched)'.DisplayName": "Multiple Topics Matched",
    "'dialog(cr3b2_test.topic.MultipleTopicsMatched)'.Description": "This system topic triggers when the bot matches multiple Topics with the incoming message and needs to clarify which one should be triggered.",
    "'dialog(cr3b2_test.topic.MultipleTopicsMatched)'.'trigger(main)'.'action(question_zf2HhP)'.Prompt.Text[0]": "To clarify, did you mean:",
    "'customEntity(cr3b2_test.entity.Wearings)'.DisplayName": "Wearings",
    "'customEntity(cr3b2_test.entity.Wearings)'.Entity.'closedListItem(ioWjXY)'.DisplayName": "Shoes",
    "'customEntity(cr3b2_test.entity.Wearings)'.Entity.'closedListItem(ioWjXY)'.Synonyms[0]": "sport shoes",
    "'customEntity(cr3b2_test.entity.Wearings)'.Entity.'closedListItem(ioWjXY)'.Synonyms[1]": "formal shoes",
    "'customEntity(cr3b2_test.entity.Wearings)'.Entity.'closedListItem(ioWjXY)'.Synonyms[2]": "sneakers",
    "'customEntity(cr3b2_test.entity.Wearings)'.Entity.'closedListItem(ioWjXY)'.Synonyms[3]": "boots",
    "'customEntity(cr3b2_test.entity.Wearings)'.Entity.'closedListItem(ioWjXY)'.Synonyms[4]": "spikes",
    "'customEntity(cr3b2_test.entity.Wearings)'.Entity.'closedListItem(aVUzb6)'.DisplayName": "Sandals",
    "'customEntity(cr3b2_test.entity.Wearings)'.Entity.'closedListItem(aVUzb6)'.Synonyms[0]": "flip flops",
    "'customEntity(cr3b2_test.entity.Wearings)'.Entity.'closedListItem(aVUzb6)'.Synonyms[1]": "Slippers",
    "'customEntity(cr3b2_test.entity.Wearings)'.Entity.'closedListItem(l4DlxJ)'.DisplayName": "Cloth",
    "'customEntity(cr3b2_test.entity.Wearings)'.Entity.'closedListItem(l4DlxJ)'.Synonyms[0]": "joggers",
    "'customEntity(cr3b2_test.entity.Wearings)'.Entity.'closedListItem(l4DlxJ)'.Synonyms[1]": "boxers",
    "'customEntity(cr3b2_test.entity.Wearings)'.Entity.'closedListItem(l4DlxJ)'.Synonyms[2]": "t-shirts",
    "'customEntity(cr3b2_test.entity.Wearings)'.Entity.'closedListItem(l4DlxJ)'.Synonyms[3]": "trousers",
    "'customEntity(cr3b2_test.entity.Wearings)'.Entity.'closedListItem(l4DlxJ)'.Synonyms[4]": "shirts",
    "'dialog(cr3b2_test.topic.Lesson3)'.DisplayName": "Lesson 3 - A topic with a condition, variables and a pre-built entity",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.'action(Sjghab)'.Activity.Text[0]": "I am happy to help you place your order.",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.'action(eRH3BJ)'.Prompt.Text[0]": "To what state will you be shipping?",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.'action(X7BFUC)'.Activity.Text[0]": "There will be an additional shipping charge of $27.50.",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.'action(6lyBi8)'.Prompt.Text[0]": "Is that acceptable?",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.'action(LMwySU)'.Activity.Text[0]": "Thank you and please come again.",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.'action(mgz1sJ)'.Prompt.Text[0]": "What item are you interested in purchasing? We are focused on a few quality items.",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.'action(mgz1sJ)'.Entity.Definition.'closedListItem(Desktop Computer)'.DisplayName": "Desktop Computer",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.'action(mgz1sJ)'.Entity.Definition.'closedListItem(Laptop Computer)'.DisplayName": "Laptop Computer",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.'action(mgz1sJ)'.Entity.Definition.'closedListItem(Gaming Computer)'.DisplayName": "Gaming Computer",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.'action(PjNoWL)'.Activity.Text[0]": "Great choice for the desktop publisher!",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.'action(vj6Vbx)'.Activity.Text[0]": "Great choice for the on-the-go road warrior!",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.'action(25VVXi)'.Activity.Text[0]": "Go get 'em tiger! Sudoku helps keep the mind active.",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.'action(L3bEHg)'.Activity.Text[0]": "I am adding\u00A0{Topic.Item} to your cart.",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.'action(529q62)'.Activity.Text[0]": "To complete your order, please go to your cart.\n\nThank you!",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.Intent.DisplayName": "Lesson 3 - A topic with a condition, variables and a pre-built entity",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.Intent.TriggerQueries[0]": "Buy items",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.Intent.TriggerQueries[1]": "Buy online",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.Intent.TriggerQueries[2]": "Buy product",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.Intent.TriggerQueries[3]": "Purchase item",
    "'dialog(cr3b2_test.topic.Lesson3)'.'trigger(main)'.Intent.TriggerQueries[4]": "Order product",
    "'dialog(cr3b2_test.topic.Goodbye)'.DisplayName": "Goodbye",
    "'dialog(cr3b2_test.topic.Goodbye)'.Description": "This topic triggers when the user says goodbye. By default, it does not end the conversation. If you would like to end the conversation when the user says goodbye, you can add an \"End of Conversation\" action to this topic, or redirect to the \"End of Conversation\" system topic.",
    "'dialog(cr3b2_test.topic.Goodbye)'.'trigger(main)'.'action(question_zf2HhP)'.Prompt.Text[0]": "Would you like to end our conversation?",
    "'dialog(cr3b2_test.topic.Goodbye)'.'trigger(main)'.'action(sendMessage_LdLhmf)'.Activity.Text[0]": "Go ahead. I'm listening.",
    "'dialog(cr3b2_test.topic.Goodbye)'.'trigger(main)'.Intent.DisplayName": "Goodbye",
    "'dialog(cr3b2_test.topic.Goodbye)'.'trigger(main)'.Intent.TriggerQueries[0]": "Bye",
    "'dialog(cr3b2_test.topic.Goodbye)'.'trigger(main)'.Intent.TriggerQueries[1]": "Bye for now",
    "'dialog(cr3b2_test.topic.Goodbye)'.'trigger(main)'.Intent.TriggerQueries[2]": "Bye now",
    "'dialog(cr3b2_test.topic.Goodbye)'.'trigger(main)'.Intent.TriggerQueries[3]": "Good bye",
    "'dialog(cr3b2_test.topic.Goodbye)'.'trigger(main)'.Intent.TriggerQueries[4]": "No thank you. Goodbye.",
    "'dialog(cr3b2_test.topic.Goodbye)'.'trigger(main)'.Intent.TriggerQueries[5]": "See you later",
    "'dialog(cr3b2_test.topic.Escalate)'.DisplayName": "Escalate",
    "'dialog(cr3b2_test.topic.Escalate)'.Description": "This system topic is triggered when the user indicates they would like to speak to a human agent.\nYou can configure how the bot will handle human hand-off scenarios in the bot settings.\nIf your bot does not handle escalations, this topic should be disabled.",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.'action(sendMessage_s39DCt)'.Activity.Text[0]": "Escalating to a live agent is not currently configured for this bot, however this is where the bot could provide information about how to get in touch with someone another way.\n\nIs there anything else I can help you with?",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.DisplayName": "Escalate",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[0]": "Talk to agent",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[1]": "Talk to a person",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[2]": "Talk to someone",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[3]": "Call back",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[4]": "Call customer service",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[5]": "Call me please",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[6]": "Call support",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[7]": "Call technical support",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[8]": "Can an agent call me",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[9]": "Can I call",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[10]": "Can I get in touch with someone else",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[11]": "Can I get real agent support",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[12]": "Can I get transferred to a person to call",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[13]": "Can I have a call in number Or can I be called",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[14]": "Can I have a representative call me",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[15]": "Can I schedule a call",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[16]": "Can I speak to a representative",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[17]": "Can I talk to a human",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[18]": "Can I talk to a human assistant",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[19]": "Can someone call me",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[20]": "Chat with a human",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[21]": "Chat with a representative",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[22]": "Chat with agent",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[23]": "Chat with someone please",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[24]": "Connect me to a live agent",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[25]": "Connect me to a person",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[26]": "Could some one contact me by phone",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[27]": "Customer agent",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[28]": "Customer representative",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[29]": "Customer service",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[30]": "I need a manager to contact me",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[31]": "I need customer service",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[32]": "I need help from a person",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[33]": "I need to speak with a live argent",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[34]": "I need to talk to a specialist please",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[35]": "I want to talk to customer service",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[36]": "I want to proceed with live support",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[37]": "I want to speak with a consultant",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[38]": "I want to speak with a live tech",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[39]": "I would like to speak with an associate",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[40]": "I would like to talk to a technician",
    "'dialog(cr3b2_test.topic.Escalate)'.'trigger(main)'.Intent.TriggerQueries[41]": "Talk with tech support member"
  }